### ISSUE TITLE
[BUG] Quick Strike only works in creative mode - because of inventory changes.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#41]
Slimeking is having this issue too.

**Comment by pearuhdox** [comment]
This bug ties to the enchant calculator issue, it specifically happens because the item with Quick Strike takes durability damage thus forcing an inventory update. When the calculation system is revamped, this should be fixed. I will leave this issue open for now but will relate it to https://github.com/pearuhdox/Cartographer-2.0/issues/7

I will also tag it with priority but this should be fixed with the overhaul of the calculation system.

**Comment by pearuhdox** [comment]
Fixed with Issue #7
