### ISSUE TITLE
Bows can use Recoil when not fully charged

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#42]

**Comment by pearuhdox** [comment]
This is intentional and how Recoil worked in the previous iterations of Cartographer with Repeating. This interaction will not be changed going forward, though the airborn momentum mechanics may be altered in the future pending actual playtesting, The current stance on this is that it is up to the mapmaker to properly balance high Recoil items on faster firing weapons.

**Comment by pearuhdox** [comment]
Reopening this issue but changing it to "Bows can use Recoil when not fully charged"

**Comment by pearuhdox** [comment]
I have implemented a partial behavior fix for this. Bows will require at least 0.5 seconds (half the draw time) to use Recoil. However, if the bow is spammed consecutively after firing it with no tick delay, this can be abused, as draw time statistic takes 1 tick to reset so it can be used by all mechanics following it in the tick.

This draw time behavior will not be altered, but since it requires constantly drawing the bow every tick, the usefulness of this spamming is low, so it should not be an issue,
