### ISSUE TITLE
Most enchants do not work on wolves equipped with enchanted wolf armor.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#66]
Also wolf armor cannot currently be enchanted in the enchanting table.

**Comment by pearuhdox** [comment]
As for now, this will not be fixed. This is because there is no current way to detect Wolves attacking other entities in a way that is performant efficient due to a bug with enchant attack types. Enchants with post_attack criteria cannot trigger something on the user, meaning verifying the stats of the wearer when commiting to an attack is very difficult. Extending support to Wolves would require new implementations of every valid enchantment.

In the distant future, this might be worked on, but since it is not a priority for release or any currently planned content, I am marking this as closed and tagging it with "reopen".
