### ISSUE TITLE
Blacklist ghasts, guardians, slimes and magma cubes from the confused status effect.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#69]
None of the above mobs can fight other mobs.

**Comment by pearuhdox** [comment]
These entities are already marked unaffected by Confused. They can receive the confused status effect but will not attempt to target other entities. There was an issue with how the tag applies when using the status effect.

The behavior of an entity that cannot retarget other mobs in Confusion is:
`Receives the Confusion damage instance each time it would attempt to target. Will temporarily be force unaggro'd from the player when a mob target switch would be attempted. Receives Slowness 1 when target swapping fails. Confusion cannot attempt this again for 4 seconds.`

All mobs that are not allowed to target other mobs now have this behavior, rather than just individual exceptions, such as Illagers targeting Illagers.
