### ISSUE TITLE
Auto Charge and Scavenger doesn't work on Spawn Eggs

### ISSUE THREAD

**Issue by SlimeKing77777** [pearuhdox/Cartographer-2.0#79]
So Infinity does work on Spawn Eggs but Auto Charge and Scavenger doesn't? That's kinda weird.

**Comment by pearuhdox** [comment]
Infinity does not intentionally work on Spawn Eggs, so this will not be fixed. I cannot replicate Infinity working on spawn eggs myself, but it is also not a feature I plan on supporting, so this will not be changed.

**Comment by pearuhdox** [comment]
The reason this works is because the condition that detects a block being placed also inadvertently tests when a spawn egg is placed (the logic is identical) this basically means that any Spawn Egg is treated as a block for the purposes of the code, and Blocks are supported with Infinity but specifically not with Auto Charge nor Scavenger.
