### ISSUE TITLE
Add a cap to the amount of aberrations, soulfires, and eruptions that can trigger at once.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#98]
Otherwise a hyperspawner or natural spawns could allow these enchants to multiply exponentially and slow or even crash the game.

**Comment by pearuhdox** [comment]
Enchantments that are allowed to escalate like this have some established stop gaps in how they run that can limit their effectiveness.

I generally do not think this will be an issue outside of laughably absurd scenarios that are due to the mapper's poor use of entity counts, but I will keep an eye on it and modify solutions as necessary.

Tldr - at the time I do not think a cap is necessary and hurts the power fantasy of the enchantment. If it proves to be a very tangible problem I will reopen this issue. It will likely not be a cap, but modifications to how the enchants work. (Removal of Aberration splits, increased time before Eruption can reactivate, etc.)
